> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Numpy functions you should know


### Numpy functions

Write a short introduction about Numpy and list the chosen functions. 

- numpy.linspace
- numpy.argmax
- numpy.repeat
- numpy.random
- numpy.intersect1d()

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "chandan10421/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/chandan10421/numpy-array-operations


'https://jovian.ml/chandan10421/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = numpy.linspace  # (change this)
function2 = numpy.argmax
function3 = numpy.repeat
function4 = numpy.random
function5 = numpy.intersect1d()

## Function 1 - numpy.linspace

This function returns evenly spaced numbers over a specified interval.

In [5]:
# Example 1 - working (change this)
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In above example linespace method creates 11 elements of equall space and last element is included.

In [6]:
# Example 2 - working
np.linspace(0,10,11,endpoint=False)

array([0.        , 0.90909091, 1.81818182, 2.72727273, 3.63636364,
       4.54545455, 5.45454545, 6.36363636, 7.27272727, 8.18181818,
       9.09090909])

In above example linespace method creates 11 elements of equall space but when we set endpoint to false the last element is not included .

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
np.linspace(15,5,-4)

ValueError: Number of samples, -4, must be non-negative.

since the third parameter of the linespace the number of the elements of the vector hence it cannot be negative.
so  to correct this we need to provide value greater than zero.

Linspace function can be used to generate evenly spaced samples for the x-axis

In [8]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "chandan10421/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/chandan10421/numpy-array-operations


'https://jovian.ml/chandan10421/numpy-array-operations'

##  Function 2 -numpy.argmax

 This function returns the indices of the maximum values along an axis

In [9]:
# Example 1 - working
array = np.array([[1,2,3],[4,5,6]])
max_pos = np.argmax(array)
max_pos

5

The above function returns index of maximum value

In [10]:
# Example 2 - working
array = np.array([[1,2,3],[4,5,6]])
max_pos_0 = np.argmax(array, axis=0)
max_pos_0

array([1, 1, 1])

 The above function obtains the indeces of maximum values along a specified axis, providing 0 or 1 to the axis attribute

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
max_pos_1 = np.argmax(array,axis=2)
print(array.shape)
max_pos_1

AxisError: axis 2 is out of bounds for array of dimension 2

Since array has only two axis that is 0 for column and  1 row hence when you use axis=2 we get an error.
inorder to slove the above problem we can use array.shape to check the axis.

The numpy.argmax can be very useful in reinforcement learning tasks

In [12]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "chandan10421/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/chandan10421/numpy-array-operations


'https://jovian.ml/chandan10421/numpy-array-operations'

## Function 3- numpy.repeat

 This function repeats the elements of an array. The number of repetitions is specified by the second argument repeats.

In [13]:
# Example 1 - working
np.repeat(3,5)

array([3, 3, 3, 3, 3])

The above function repeat the number 3 5 times

In [14]:
# Example 2 - working
a=np.random.randint(0,5,(3,3))
np.repeat(a,2,axis=0)


array([[3, 1, 0],
       [3, 1, 0],
       [3, 2, 2],
       [3, 2, 2],
       [2, 0, 0],
       [2, 0, 0]])

The above function array a is repeated twice on axis 0

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.random.randint(0,5,(3,3))
np.repeat(a,2,axis=2)


AxisError: axis 2 is out of bounds for array of dimension 2

 Since array has only two axis therefore axis=2 gives index error we can fix this by using proper axis.

This function is very useful when dealing with pandas or data frame where we have to repeat the values for many times.

In [16]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "chandan10421/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/chandan10421/numpy-array-operations


'https://jovian.ml/chandan10421/numpy-array-operations'

In [18]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "chandan10421/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/chandan10421/numpy-array-operations


'https://jovian.ml/chandan10421/numpy-array-operations'

## Function 4 - numpy.random

This function returns random integers from the interval low , high.

In [19]:
# Example 1 - working
np.random.randint(2)

1

If high parameter is missing then by default 0 is taken as low value and low value is taken as high value.

In [20]:
# Example 2 - working
np.random.randint(2,5,size=(5,2))

array([[2, 4],
       [3, 3],
       [4, 2],
       [4, 3],
       [4, 2]])

Here the values are created from 2 to 4 and 5 is excluded and an  array size is (5,2)

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
np.random.randint(-1,-1,size=10)

ValueError: low >= high

Since the value of low is equall to high there is no number in between the two  values and hence the error is generated.
To fix this we can make sure the value of high is grater than low.

This function can be used to simulate random events such as tossing a coin, or rolling a dice .

In [22]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "chandan10421/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/chandan10421/numpy-array-operations


'https://jovian.ml/chandan10421/numpy-array-operations'

## Function 5 - numpy.intersect1d()
What intersect1d() function will do is, it will return the intersection of 2 arrays — meaning the items that are common in both arrays. Unlike the previous functions, it won't return the index position, it will return the actual values.

In [23]:
# Example 1 - working
arr1=np.array([3,1,2,5,5])
arr2=np.array([3,4,4,2,4])
np.intersect1d(arr1,arr2)

array([2, 3])

It returns common values between two vactors values 

In [24]:
# Example 2 - working
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
np.intersect1d(arr1,arr2)

array([], dtype=int64)

since there are no common elements between the two vectors it returns the empty array.

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7],[2,3])
np.intersect1d(arr1,arr2)

TypeError: Field elements must be 2- or 3-tuples, got '2'

since arr2 is a 2D array hence intersect1d function raises an error as it find common  values on 1D array to fix this we can  to use np.squeeze on arr2 to convert it into 1D array.

it can be usd with sets to get the intersetion of two 1D arrays.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "chandan10421/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/chandan10421/numpy-array-operations


'https://jovian.ml/chandan10421/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "chandan10421/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/chandan10421/numpy-array-operations


'https://jovian.ml/chandan10421/numpy-array-operations'